[Application Options]
listen=127.0.0.1:9735
rpclisten=localhost:10001
restlisten=127.0.0.1:8081
alias=Alice
[Bitcoin]
bitcoin.active=true
bitcoin.regtest=true
bitcoin.node=bitcoind
[Bitcoind]
bitcoind.rpchost=127.0.0.1:18443
bitcoind.rpcuser=bootcamp
bitcoind.rpcpass=bootcamp123
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
