[Application Options]
listen=127.0.0.1:9736
rpclisten=localhost:10002
restlisten=127.0.0.1:8082
alias=Bob
[Bitcoin]
bitcoin.active=true
bitcoin.regtest=true
bitcoin.node=bitcoind
[Bitcoind]
bitcoind.rpchost=127.0.0.1:18443
bitcoind.rpcuser=bootcamp
bitcoind.rpcpass=bootcamp123
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
